services:
  drizzle:
    image: drizzle-neo
    container_name: drizzle-neo
    ports:
      - "5000:5000"
    volumes:
      - ./state:/app/state:z
      - ./config.json:/app/config.json:z
    environment:
      - API_PASSWORD=secret123
    restart: unless-stopped

#services:
#  drizzle:
#    image: drizzle-neo-full
#    container_name: drizzle-neo-full
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./state:/app/state:z
#      - ./config.json:/app/config.json:z
#      - ./prompt.py:/app/prompt.py:z
#      - ./models:/app/models:z
#    environment:
#      - API_PASSWORD=secret123
#    restart: unless-stopped
